# Generated by Django 4.0.6 on 2022-07-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre: ')),
                ('apellido', models.CharField(max_length=10, verbose_name='Apellido')),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('0', 'Hombre'), ('1', 'Mujer'), ('2', 'otro')], max_length=1, verbose_name='Sexo')),
                ('parentezco', models.CharField(choices=[('0', 'Padre'), ('1', 'Madre'), ('2', 'Hijos')], max_length=1, verbose_name='Parentezco Familiar:')),
                ('dni', models.CharField(max_length=10, verbose_name='DNI:')),
                ('fecha_nac', models.DateField(verbose_name='Fecha Nacimiento: ')),
            ],
        ),
    ]
