# Generated by Django 4.0.6 on 2022-07-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='fecha_nac',
            field=models.DateTimeField(verbose_name='Fecha Nacimiento: '),
        ),
    ]
