# Generated by Django 4.0.6 on 2022-07-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0003_remove_familia_fecha_nac'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento: '),
        ),
        migrations.AlterField(
            model_name='familia',
            name='parentezco',
            field=models.CharField(choices=[('0', 'Padre'), ('1', 'Madre'), ('2', 'Hijo')], max_length=1, verbose_name='Parentezco Familiar:'),
        ),
    ]
