# Generated by Django 4.0.6 on 2022-08-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0004_familia_fecha_nac_alter_familia_parentezco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('precio', models.IntegerField()),
                ('fecha_v', models.DateField(verbose_name='Fecha venta')),
            ],
        ),
    ]
